name: missile_env
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - et_xmlfile=1.1.0
  - expat=2.6.2
  - intel-openmp=2023.1.0
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openpyxl=3.1.2
  - openssl=3.0.13
  - pandas=2.2.1
  - pip=24.0
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - setuptools=69.5.1
  - simplekml=1.3.6
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
