"""Specify initial config data for Dash app."""

import datetime
from typing import Dict, List

def init_data() -> List[Dict]:
    """Get initial config data for Dash app."""
    return [
     {'Parameter': 'missile_name',
      'Description': 'unique name for the missile folder',
      'Dtype': 'str',
      'Simulation1': 'missile1',
      'Simulation2': 'missile2',
      'Simulation3': 'missile3',
      'Simulation4': 'missile4',
      'Simulation5': 'missile5',
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'group_name',
      'Description': 'unique or shared name for the KMZ file',
      'Dtype': 'str',
      'Simulation1': 'test_group1',
      'Simulation2': 'test_group1',
      'Simulation3': 'test_group2',
      'Simulation4': 'test_group2',
      'Simulation5': 'test_group2',
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'launch_date',
      'Description': 'date of missile launch (mm/dd/yyyy)',
      'Dtype': 'object',
      'Simulation1': datetime.datetime(2020, 7, 30, 0, 0),
      'Simulation2': datetime.datetime(2020, 7, 30, 0, 0),
      'Simulation3': datetime.datetime(2020, 7, 30, 0, 0),
      'Simulation4': datetime.datetime(2020, 7, 30, 0, 0),
      'Simulation5': datetime.datetime(2020, 7, 30, 0, 0),
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'launch_time_UTC',
      'Description': 'time of missile launch (HH:mm:ss UTC)',
      'Dtype': 'object',
      'Simulation1': datetime.time(4, 0),
      'Simulation2': datetime.time(4, 0, 30),
      'Simulation3': datetime.time(4, 0, 45),
      'Simulation4': datetime.time(4, 1, 30),
      'Simulation5': datetime.time(4, 2),
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'LP_lat_deg',
      'Description': 'launchpoint latitude (decimal degrees)',
      'Dtype': 'float',
      'Simulation1': 39.516825,
      'Simulation2': 39.485511,
      'Simulation3': 39.504076,
      'Simulation4': 39.542741,
      'Simulation5': 39.521769,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'LP_lon_deg',
      'Description': 'launchpoint longitude (decimal degrees)',
      'Dtype': 'float',
      'Simulation1': -104.95567,
      'Simulation2': -104.884624,
      'Simulation3': -104.903619,
      'Simulation4': -104.976897,
      'Simulation5': -105.013038,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'AP_lat_deg',
      'Description': 'aimpoint latitude (decimal degrees)',
      'Dtype': 'float',
      'Simulation1': 40.862397,
      'Simulation2': 40.862397,
      'Simulation3': 40.862397,
      'Simulation4': 40.862397,
      'Simulation5': 40.862397,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'AP_lon_deg',
      'Description': 'aimpoint longitude (decimal degrees)',
      'Dtype': 'float',
      'Simulation1': -105.025902,
      'Simulation2': -105.025902,
      'Simulation3': -105.025902,
      'Simulation4': -105.025902,
      'Simulation5': -105.025902,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'horizontal_velocity_km_sec',
      'Description': 'horizontal velocity of missile (km/s)',
      'Dtype': 'float',
      'Simulation1': 1,
      'Simulation2': 1,
      'Simulation3': 1,
      'Simulation4': 1,
      'Simulation5': 1,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'timestep_sec',
      'Description': 'simulation timestep (seconds)',
      'Dtype': 'float',
      'Simulation1': 1,
      'Simulation2': 1,
      'Simulation3': 1,
      'Simulation4': 1,
      'Simulation5': 1,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'sim_start_time_buffer_sec',
      'Description': 'time before launch to start simulation (seconds)',
      'Dtype': 'float',
      'Simulation1': 10,
      'Simulation2': 10,
      'Simulation3': 10,
      'Simulation4': 10,
      'Simulation5': 10,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'sim_end_time_buffer_sec',
      'Description': 'time after impact to end simulation (seconds)',
      'Dtype': 'float',
      'Simulation1': 10,
      'Simulation2': 10,
      'Simulation3': 10,
      'Simulation4': 10,
      'Simulation5': 10,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'collada_model_dir',
      'Description': 'directory containing  3D COLLADA model',
      'Dtype': 'str',
      'Simulation1': '../Blender',
      'Simulation2': '../Blender',
      'Simulation3': '../Blender',
      'Simulation4': '../Blender',
      'Simulation5': '../Blender',
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'collada_model_file',
      'Description': 'file name of 3D COLLADA model (.dae)',
      'Dtype': 'str',
      'Simulation1': 'test_missile.dae',
      'Simulation2': 'test_missile.dae',
      'Simulation3': 'test_missile.dae',
      'Simulation4': 'test_missile.dae',
      'Simulation5': 'test_missile.dae',
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""},
     {'Parameter': 'collada_model_scale',
      'Description': 'scale factor for all 3D model axes (x, y, z)',
      'Dtype': 'int',
      'Simulation1': 500,
      'Simulation2': 500,
      'Simulation3': 500,
      'Simulation4': 500,
      'Simulation5': 500,
      'Simulation6': "",
      'Simulation7': "",
      'Simulation8': "",
      'Simulation9': "",
      'Simulation10': ""}]